LojaProdutosCurso/Controllers/EstoqueController.cs
using ClosedXML.Excel;
using LojaProdutosCurso.Services.Estoque;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace LojaProdutosCurso.Controllers
{
    public class EstoqueController : Controller
    {
        private readonly IEstoqueInterface _estoqueInterface;

        public EstoqueController(IEstoqueInterface estoqueInterface)
        {
            _estoqueInterface = estoqueInterface;
        }
        public IActionResult Index()
        {
            var registros = _estoqueInterface.ListagemRegistros();
            return View(registros);
        }

        public IActionResult GerarRelatorio()
        {
            //Buscar os dados

            var dados = BusacaDados();

            //Retornar o arquivo
            using (XLWorkbook workbook = new XLWorkbook())
            {
                workbook.Worksheets.Add(dados, "Dados Vendas");

                using (MemoryStream stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    return File(
                        content,
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        "Relatorio_Vendas_Produtos.xlsx");
                }
            }
        }
        private DataTable BusacaDados()
        {
            DataTable dataTable = new DataTable();
            dataTable.TableName = "Dados Vendas -  Produtos";

            dataTable.Columns.Add("ProdutoId", typeof(int));
            dataTable.Columns.Add("Categoria", typeof(string));
            dataTable.Columns.Add("Data da Compra", typeof(DateTime));
            dataTable.Columns.Add("Valor Total", typeof(decimal));


            var dados = _estoqueInterface.ListagemRegistros();

            if(dados.Count > 0)
            {
                foreach (var registro in dados)
                {
                    dataTable.Rows.Add(
                        registro.ProdutoId,
                        registro.CategoriaNome,
                        registro.DataCompra,
                        registro.TotalGeral
                    );
                }
            }
            return dataTable;
        }

        [HttpPost]
        public async Task<IActionResult> BaixarEstoque(int id)
        {
            var produtoBaixado = await _estoqueInterface.CriarRegistro(id);
            TempData["MensagemSucesso"] = "Compra Realizada com Sucesso!";
            return RedirectToAction("Index", "Home");
        }
    }
}

LojaProdutosCurso/Controllers/UsuarioController.cs
using AutoMapper;
using LojaProdutosCurso.DTO.Endereco;
using LojaProdutosCurso.DTO.Usuario;
using LojaProdutosCurso.Services.Usuario;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Threading.Tasks;

namespace LojaProdutosCurso.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuariointerface _usuarioInterface;
        private readonly IMapper _mapper;

        public UsuarioController(IUsuariointerface usuarioInterface, IMapper mapper)
        {
            _usuarioInterface = usuarioInterface;
            this._mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            //Pega todos os usuarios do banco 
            var usuarios = await _usuarioInterface.BuscarUsuarios();
            return View(usuarios);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        public async Task<IActionResult> Editar(int id)
        {
            var usuario = await _usuarioInterface.BuscarUsuarioPorId(id);
            var usuarioEditado = new EditarUsuarioDTO()
            {
                Id = usuario.Id,
                Nome = usuario.Nome,
                Email = usuario.Email,
                Cargo = usuario.Cargo,
                Endereco = _mapper.Map<EditarEnderecoDTO>(usuario.Endereco)
            };

            return View(usuarioEditado);
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(CriarUsuarioDTO criarUsuarioDTO)
        {
            if(ModelState.IsValid)
            {
                if(await _usuarioInterface.VerifcaSeExisteEmail(criarUsuarioDTO))
                {
                    TempData["MensagemErro"] = "E-mail já cadastrado !";
                    return View(criarUsuarioDTO);
                }
                var usuarioCadastrado = await _usuarioInterface.CadastrarUsuario(criarUsuarioDTO);

                if(usuarioCadastrado != null)
                {
                    TempData["MensagemSucesso"] = "Usuário cadastrado com sucesso !";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["MensagemErro"] = "Houve um erro ao cadastrar o usuário, tente novamente !";
                    return View(criarUsuarioDTO);
                }
            }
            else
            {
                TempData["MensagemErro"] = "Dados invalidos, verifique e tente novamente !";
                return View(criarUsuarioDTO);
            }
        }
    }
}

LojaProdutosCurso/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LojaProdutosCurso</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Brite.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LojaProdutosCurso.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link href="https://cdn.datatables.net/v/dt/dt-2.3.4/datatables.min.css" rel="stylesheet" integrity="sha384-pmGS6IIcXhAVIhcnh9X/mxffzZNHbuxboycGuQQoP3pAbb0SwlSUUHn2v22bOenI" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LojaProdutosCurso</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Estoque" asp-action="Index">Listagem Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Usuario" asp-action="Index">Usuários</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - LojaProdutosCurso - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.3.4/datatables.min.js" integrity="sha384-X2pTSfom8FUa+vGQ+DgTCSyBZYkC1RliOduHa0X96D060s7Q//fnOh3LcazRNHyo" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>